services:

  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - sakoo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  sakoo.app:
    build:
      context: .
      dockerfile: vendor/sakoo/framework-core/docker/sakoo.app/Dockerfile
    image: sakoo.app:1.0.0
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysql
    networks:
      - sakoo

  nginx:
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_PORT_SECURE:-443}:443'
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/nginx/logs/:/var/log/nginx/
    depends_on:
      - sakoo.app
    networks:
      - sakoo
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]

volumes:
  mysqldata:
    driver: local

networks:
  sakoo:
    driver: bridge