name: CI Pipeline

on:
  push:
    branches: 
      - '**'

  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Code style check
      run: composer stylecheck

    - name: Build docker image
      run: |
        docker build . -f ./vendor/sakoo/framework-core/docker/sakoo.app/Dockerfile -t sakoo.app -q

    - name: Run automated tests
      run: |
        docker run -v /home/runner/work/framework-php/framework-php:/var/www/html/ sakoo.app composer test